### ISSUE TITLE
2-qubit Reduction Not Working Properly for BeH2 at 2.5A

### ISSUE THREAD

**Issue by pistoia** [Qiskit/aqua-chemistry#16]
When computing the ground state molecular energy of BeH2 with the length of the two bonds set to 2.5A, the parity-based precision-preserving 2-qubit reduction with parity mapping correctly preserves the number of particles, but fails to compute the correct energy and dipole values.  Switching to the Jordan-Wigner value fixes the problem, but the 2-qubit reduction can no longer be applied and so we miss the opportunity to reduce the number of qubits necessary to complete the computation.

## Expected Behavior
We expect BEH2, with bond lengths both set to 2.5A, and with a configuration that includes parity mapping and 2-qubit reduction to produce correct energy and dipole values, matching what we obtain with the Jordan-Wigner mapping.

## Current Behavior
As described above, when computing the ground state molecular energy of BeH2 with the length of the two bonds set to 2.5A, the parity-based precision-preserving 2-qubit reduction with parity mapping correctly preserves the number of particles, but fails to compute the correct energy and dipole values.  Switching to the Jordan-Wigner value fixes the problem, but the 2-qubit reduction can no longer be applied and so we miss the opportunity to reduce the number of qubits necessary to complete the computation.

## Possible Solution
Investigate if parameters need to be tuned further or there is a bug in the code.

## Steps to Reproduce (for bugs)
Tanvi Gujarati and Julia Rice can provide the exact configuration.

## Context
Tanvi Gujarati and Julia Rice can provide the exact configuration.

## Your Environment
Tanvi Gujarati and Julia Rice can provide the exact configuration.

**Comment by woodsp-ibm** [comment]
As far as I can tell, using ExactEigensolver, with the molecule BeH2 in sto-3g with frozen core I see the same value whether I use parity (with or with 2 qubit reduction) or jordan wigner. The result we compute (using on PySCF driver) agrees with an FCI computation from PSI4 to 8 decimal places.

PSI4: FCI -15.35149107406431

ExactEignesolver:
-15.351491075144 Parity + 2 qubit reduction
-15.351491075144 Parity
-15.351491075144 Jordan Wigner**

**Comment by tanvipg** [comment]
For distance between Be-H at 2.5A in BeH2, we are able to get right values of energy, dipole moment and spin with 2-qubit reduction when using UCCSD with d = 2. For UCCSD with d = 1, the energy values do not match the exact eigenenergy calculations. Similarly, we are able to get the right energy, dipole moment and spin with SWAPRZ+Jordan-wigner mapping(ent = full) +particle-hole transformation using depth = 15. The details are provided in the attached spreadsheet.
[BeH2_2.5A.xlsx](https://github.com/Qiskit/aqua-chemistry/files/2283607/BeH2_2.5A.xlsx)

**Comment by woodsp-ibm** [comment]
From the above results and discussion the two_qubit_reduction is working properly so I am closing this. It does seem to be a "tuning" problem that when using VQE at those distances it needs care with the var form and configuration for it to converge down to FCI energy value.

**Comment by rugantio** [comment]
Hello, I also ran into this problem, it seems that **two_qubit_reduction** is behaving strangely only (?) when the **core** is **frozen**. In the following snippet I show that using the programmatic and the declarative approach yield two different energy answers:
```
from qiskit_chemistry import QiskitChemistry
from pprint import pprint

qiskit_chemistry_dict = {
    'driver': {'name': 'PYSCF'},
    'PYSCF': {'atom': 'H .0 .0 -1.3264; Be .0 .0 .0; H .0 .0 1.3264', 'basis': 'sto-3g'},
    'operator': {'name': 'hamiltonian', 'qubit_mapping': 'parity',
                 'two_qubit_reduction': True, 'freeze_core': True},
    'algorithm': {'name': 'ExactEigensolver'}
}

solver = QiskitChemistry()
result = solver.run(qiskit_chemistry_dict)
pprint(result['printable'])
```
Returns:


>  ['=== GROUND STATE ENERGY ===',
>  ' ',
>  '* Electronic ground state energy (Hartree): -18.98597659933',
>  '  - computed part:      -3.950718246173',
>  '  - frozen energy part: -15.035258353156',
>  '  - particle hole part: 0.0',
>  '~ Nuclear repulsion energy (Hartree): 3.391138640546',
>  '> Total ground state energy (Hartree): -15.594837958784',

Using the API instead:

```
from qiskit_chemistry import FermionicOperator
from qiskit_aqua.algorithms.classical import ExactEigensolver
from qiskit_chemistry.drivers import PySCFDriver

drv = PySCFDriver(atom='H .0 .0 -1.3264; Be .0 .0 .0; H .0 .0 1.3264', charge=0,spin=0, basis='sto-3g')
molecule = drv.run()
num_spin_orbitals = 2*molecule.num_orbitals
num_electrons = molecule.num_alpha + molecule.num_beta
print("molecule: {}, basis: sto-3g, num electrons: {}".format(molecule.atom_symbol,num_electrons))
print("\tnum_orbitals: {}, num_spin_orbitals: {}".format(molecule.num_orbitals,num_spin_orbitals))

freeze_list = [0]
freeze_list += [x + molecule.num_orbitals for x in freeze_list]
energy_shift = 0.0

f = FermionicOperator(h1=molecule.one_body_integrals, h2=molecule.two_body_integrals)
f, energy_shift = f.fermion_mode_freezing(freeze_list)
num_spin_orbitals -= len(freeze_list)
print("\tfermion_mode_freezing on: {}, num_electrons: {}, num_spin_orbitals: {}"\
      .format(freeze_list,num_electrons - len(freeze_list),f.modes))

q = f.mapping(map_type='parity', threshold=0.00000001)
q = q.two_qubit_reduced_operator(num_electrons) 
print("\tmapping: 'parity' with two_qubit_reduced_operator, num_qubits: {}".format(q.num_qubits))
ee = ExactEigensolver(q, k=1)
eig = ee.run()
print("\tcomputed energy: {}, energy_shift: {}, nuclear_repulsion_energy: {}"
      .format(eig['eigvals'][0].real,energy_shift,molecule.nuclear_repulsion_energy))
print('\ttotal energy:', eig['eigvals'][0].real + energy_shift + molecule.nuclear_repulsion_energy)
```
Returning:
> molecule: ['H', 'Be', 'H'], basis: sto-3g, num electrons: 6
> 	num_orbitals: 7, num_spin_orbitals: 14
> 	fermion_mode_freezing on: [0, 7], num_electrons: 4, num_spin_orbitals: 12
> 	mapping: 'parity' with two_qubit_reduced_operator, num_qubits: 10
> 	computed energy: -3.6879385548419945, energy_shift: -15.035258353156205, nuclear_repulsion_energy: 3.391138640545839
> 	total energy: -15.332058267452362

From which you can see that the computed energy is different and thus the total energy. 
Without the core freezing two_qubit_reduction works fine, it's easy to prove this, simplifying the code above:

```
from qiskit_chemistry import QiskitChemistry
from pprint import pprint

qiskit_chemistry_dict = {
    'driver': {'name': 'PYSCF'},
    'PYSCF': {'atom': 'H .0 .0 -1.3264; Be .0 .0 .0; H .0 .0 1.3264', 'basis': 'sto-3g'},
    'operator': {'name': 'hamiltonian', 'qubit_mapping': 'parity',
                 'two_qubit_reduction': True, 'freeze_core': False},
    'algorithm': {'name': 'ExactEigensolver'}
}

solver = QiskitChemistry()
result = solver.run(qiskit_chemistry_dict)
pprint(result['printable'])
```

> ['=== GROUND STATE ENERGY ===',
>  ' ',
>  '* Electronic ground state energy (Hartree): -18.986315509469',
>  '  - computed part:      -18.986315509469',
>  '  - frozen energy part: 0.0',
>  '  - particle hole part: 0.0',
>  '~ Nuclear repulsion energy (Hartree): 3.391138640546',
>  '> Total ground state energy (Hartree): -15.595176868923',
```
from qiskit_chemistry import FermionicOperator
from qiskit_aqua.algorithms.classical import ExactEigensolver
from qiskit_chemistry.drivers import PySCFDriver

drv = PySCFDriver(atom='H .0 .0 -1.3264; Be .0 .0 .0; H .0 .0 1.3264', charge=0,spin=0, basis='sto-3g')
molecule = drv.run()
num_spin_orbitals = 2*molecule.num_orbitals
num_electrons = molecule.num_alpha + molecule.num_beta
print("molecule: {}, basis: sto-3g, num electrons: {}".format(molecule.atom_symbol,num_electrons))
print("\tnum_orbitals: {}, num_spin_orbitals: {}".format(molecule.num_orbitals,num_spin_orbitals))

energy_shift = 0.0
f = FermionicOperator(h1=molecule.one_body_integrals, h2=molecule.two_body_integrals)
q = f.mapping(map_type='parity', threshold=0.00000001)
q = q.two_qubit_reduced_operator(num_electrons) 
print("\tmapping: 'parity' with two_qubit_reduced_operator, num_qubits: {}".format(q.num_qubits))
ee = ExactEigensolver(q, k=1)
eig = ee.run()
print("\tcomputed energy: {}, energy_shift: {}, nuclear_repulsion_energy: {}"
      .format(eig['eigvals'][0].real,energy_shift,molecule.nuclear_repulsion_energy))
print('\ttotal energy:', eig['eigvals'][0].real + energy_shift + molecule.nuclear_repulsion_energy)

```
> molecule: ['H', 'Be', 'H'], basis: sto-3g, num electrons: 6
> 	num_orbitals: 7, num_spin_orbitals: 14
> 	mapping: 'parity' with two_qubit_reduced_operator, num_qubits: 12
> 	computed energy: -18.986315509469136, energy_shift: 0.0, nuclear_repulsion_energy: 3.391138640545839
> 	total energy: -15.595176868923298
