### ISSUE TITLE
Multiprocessing pickle error with pluggable classes

### ISSUE THREAD

**Issue by ss2165** [Qiskit/aqua-chemistry#57]
### Informations

- **Qiskit Aqua Chemistry version**:0.3.1
- **Python version**:3.6.3
- **Operating system**: macos 10.14.1

### What is the current behavior?
parallelising using multiprocessing involving any class fetched via get_pluggable_class fails because pickle fails to pickle these classes. Seems to work if they are imported normally.

### Steps to reproduce the problem
try multiprocessing.Pool().map() with a function that is a method of an instance of class from get_pluggable_class

### What is the expected behavior?

gets pickled

**Comment by chunfuchen** [comment]
Hi @ss2165, we updated the Aqua to make the pluggable class can be pickled. do you mind pull the newest changes in Aqua to test it?

Here is his PR: https://github.com/Qiskit/aqua/pull/209

**Comment by ss2165** [comment]
Thanks, it works fine now (though, if you don't mind asking, is using 'exec' the best way to go about it?)

**Comment by manoelmarques** [comment]
Pickle inside the multiprocessing library won't work unless the class used is imported. It doesn't work with code loaded through importlib, hence the use of 'exec' to import it. More info can be found at: https://medium.com/@jwnx/multiprocessing-serialization-in-python-with-pickle-9844f6fa1812 

Of course we are open in case you have a better solution.
